### ISSUE TITLE
スクロールできなくなる

### ISSUE THREAD

**Issue by Mijikko** [MijinkoSD/Scrapbox_Settings_20230126-#1]
## 修正用CSS

```css
@media (min-width: 768px) and (min-height: 500px) {
  .app.app > .page-item-animation + .container:not([style]) {
    /* プロジェクトタイトル */
    position: absolute;
    margin: 0;
    z-index: 1020;
  }
  .app.app > .container:not([style]) {
    position: static;
    z-index: unset;
  }
  div.quick-launch.layout-page {
    position: fixed;
    top: var(--navbar-row-1-height);
  }
  .page-wrapper.page-wrapper {
    margin-top: 0;
  }
}
```
